ARG RUBY_VERSION=3.2.3
FROM ruby:${RUBY_VERSION}-slim AS base

ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3 \
    BUNDLE_PATH=/usr/local/bundle

WORKDIR /rails

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    bash curl ca-certificates git build-essential pkg-config \
    default-libmysqlclient-dev default-mysql-client libssl-dev tzdata \
 && rm -rf /var/lib/apt/lists/*

RUN gem install bundler -N

# 依存だけ先に解決してキャッシュを効かせる
COPY Gemfile Gemfile.lock ./
RUN bundle config set force_ruby_platform true \
 && bundle install

# アプリ本体を最後にCOPY
COPY . .

# エントリポイントを実行可能に
RUN chmod +x ./bin/compose-entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["bash", "-lc", "./bin/compose-entrypoint.sh"]
