AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Genba Tasks - Demo API (guest only)"

Parameters:
  AllowedOrigin:
    Type: String
    Default: https://app.genba-tasks.com
  StageName:
    Type: String
    Default: prod

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 128
    Timeout: 5
    Architectures: [ arm64 ]
    Tracing: Active
    Environment:
      Variables:
        ALLOWED_ORIGIN: !Ref AllowedOrigin

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      CorsConfiguration:
        AllowOrigins:
          - !Ref AllowedOrigin
        AllowMethods:
          - GET
          - POST
          - PATCH
          - DELETE
          - OPTIONS
        # ← ここを *全部小文字* に
        AllowHeaders:
          - content-type
          - authorization
          - x-auth-start
          - access-token
          - client
          - uid
          - token-type
          - expiry
        MaxAge: 86400

  HealthFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.health
      Events:
        GetHealth:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /health
            Method: GET

  GuestLoginFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.guestLogin
      Events:
        PostGuestLogin:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /guest/login
            Method: POST

Outputs:
  ApiInvokeUrl:
    Description: "Invoke URL (base)"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
