name: Deploy Frontend (S3 + CloudFront)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-front.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Node を .nvmrc で指定（.nvmrcが無ければ node-version: 20 に変更）
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/.nvmrc'

      # pnpm は package.json の "packageManager" を参照
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: frontend/package.json   # ← ここを修正
          run_install: false

      # 必須の環境変数を先に検証（空なら即Failで原因が分かりやすい）
      - name: Validate env vars
        run: |
          [ -n "${{ vars.S3_BUCKET }}" ] || { echo "S3_BUCKET is empty"; exit 1; }
          [ -n "${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}" ] || { echo "CLOUDFRONT_DISTRIBUTION_ID is empty"; exit 1; }
          [ -n "${{ vars.VITE_API_BASE_URL }}" ] || { echo "VITE_API_BASE_URL is empty"; exit 1; }
          [ -n "${{ vars.AWS_REGION }}" ] || { echo "AWS_REGION is empty"; exit 1; }

      - name: Install deps
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: frontend
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
        run: pnpm build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync assets (immutable)
        working-directory: frontend
        run: |
          aws s3 sync ./dist s3://${{ vars.S3_BUCKET }}/ \
            --delete --exclude "index.html" \
            --cache-control "public,max-age=31536000,immutable"

      - name: Upload index.html (no-cache)
        working-directory: frontend
        run: |
          aws s3 cp ./dist/index.html s3://${{ vars.S3_BUCKET }}/index.html \
            --cache-control "no-cache" \
            --content-type "text/html" \
            --metadata-directive REPLACE

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html" "/"
